Refactor smornn
asurt-fsai/fs-system pull request #29
Opened 2023-02-25 09:42 UTC by kareemalsawah

2023-02-25 23:09 UTC, RoniEmad requested changes

2023-02-28 12:16 UTC, kareemalsawah commented on perception/smornn/src/smornn/SmornnRos.py
> +            landmark.type = cone[2]
Done

2023-02-28 12:48 UTC, RoniEmad submitted a review, later dismissed

2023-02-28 13:37 UTC, ahmedemad242 requested changes

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/src/smornn/helpers.py
> +"""
This code is repeated in mrpython_pcl, do you think we should have it in dependencies?

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/tests/smornn_test.py
> +from smornn import Smornn  # pylint: disable=no-name-in-module
We no longer check for pylint import errors

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/src/smornn/SmornnRos.py
> +    def toConeArray(
This function and the next one can be moved outside the class it self, or marked as static methods.

It can also be moved to a utility package if it's going to be used by other packages?

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/src/smornn/SmornnRos.py
> +    def toConeArray(
Can you also edit the names of this and the next function adding type being converted?

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/src/smornn/SmornnRos.py
> +            return cones
return None

2023-02-28 13:37 UTC, ahmedemad242 commented on perception/smornn/src/smornn/Smornn.py
> +        Returns None is no lidar detections are available
typo: Returns None if

2023-03-04 08:40 UTC, kareemalsawah commented on perception/smornn/src/smornn/helpers.py
> +"""
Yes, maybe do it in another pull request after this to not modify mrpython-pcl in this one?

2023-03-04 08:44 UTC, kareemalsawah commented on perception/smornn/nodes/smornn_node.py
> +# pylint: disable=import-error, no-name-in-module
Done

2023-03-04 08:44 UTC, kareemalsawah commented on perception/smornn/tests/smornn_test.py
> +from smornn import Smornn  # pylint: disable=no-name-in-module
Done

2023-03-04 08:45 UTC, kareemalsawah commented on perception/smornn/src/smornn/Smornn.py
> +        Returns None is no lidar detections are available
Done

2023-03-04 08:47 UTC, kareemalsawah commented on perception/smornn/src/smornn/SmornnRos.py
> +            return cones
Done

2023-03-04 09:24 UTC, kareemalsawah commented on perception/smornn/src/smornn/SmornnRos.py
> +    def toConeArray(
Removed it and used ones from tf helper

2023-03-04 09:24 UTC, kareemalsawah commented on perception/smornn/src/smornn/SmornnRos.py
> +    def toConeArray(
Removed it and used ones from tf helper

2023-03-04 09:27 UTC, ahmedemad242 commented on perception/smornn/src/smornn/helpers.py
> +"""
Sure I will add it as an issue 👍

2023-03-04 09:32 UTC, ahmedemad242 approved these changes
LGTM, Good job!

2023-03-04 11:40 UTC, RoniEmad approved these changes

2023-03-06 21:10 UTC, merged