Refactor smoreo
asurt-fsai/fs-system pull request #33
Opened 2023-03-14 02:24 UTC by mo-sameh

2023-03-18 00:39 UTC, RoniEmad requested changes

2023-03-18 10:30 UTC, ahmedemad242 requested changes

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/README.md
> +Follow the instructions on the [ROS Wiki](http://wiki.ros.org/kinetic/Installation/Ubuntu) to install ROS Kinetic.
We are using ROS noetic

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/README.md
> +## License
License is included in the root directory no need to include it here

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/launch/smoreo_sys_flir.launch
> +	<!--<include file="$( find bounding_box_filter)/launch/bounding_box_filter.launch"/>-->
remove unnecessary comments

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/launch/smoreo_sys_ipg.launch
> +	<!--<include file="$( find bounding_box_filter)/launch/bounding_box_filter.launch"/>-->
remove unnecessary comments

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/src/__init__.py
There should be no init.py in the src folder

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/package.xml
> +  <!-- The export tag contains other, unspecified, tags -->
remove unnecessary comments

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/testing/generateTestCase.py
> +    BAG_PATH = "/media/mosameh/CEFE-EBFE/first_Ipg_moreo_inputs.bag"
you cannot use absolute paths from your system, please use relative paths

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/tests/__init__.py
this is not a module there is no need for an __init__.py file

2023-03-18 10:30 UTC, ahmedemad242 commented on perception/smoreo/tests/smoreo_test.py
> +            r"/home/mosameh/fs-system2/src/perception/smoreo/testing/testCase1.pickle",
you cannot use absolute paths from your system, please use relative paths

2023-03-19 00:53 UTC, RoniEmad submitted a review, later dismissed
Good for me

2023-03-20 03:22 UTC, RoniEmad submitted a review, later dismissed
LGTM

2023-03-20 14:52 UTC, ahmedemad242 submitted a review, later dismissed
LGTM! Good Job @mo-sameh @ranaamr22 

I am waiting for confirmation to merge

2023-03-20 16:38 UTC, ahmedemad242 approved these changes

2023-03-20 16:39 UTC, merged