Add purepursuit
asurt-fsai/fs-system pull request #39
Opened 2023-04-10 05:20 UTC by Mohamed-alaa32

Merging Simple pure pursuit controller to Main branch

2023-04-17 23:50 UTC, aminpaw requested changes
navigation/pure_pursuit/nodes/purepursuit_node.py
Change waypoints message type to Path instead of Pose

2023-04-18 10:37 UTC, ahmedemad242 requested changes

2023-04-18 10:37 UTC, ahmedemad242 commented on .gitignore
> +navigation/pure_pursuit/tests/waypointsgen.py
Please don't ignore specific files in the main .gitignore.
you can have a gitignore in a subdirectory to ignore what you want there.

Read this https://stackoverflow.com/questions/3719574/is-it-possible-to-ignore-gitignore-rules-in-subdirectory

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/launch/parameters.yaml
I would rather this file be a .launch file

Read the file "/perception/mrpython_pcl/launch/lidar_params.launch"

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        assert len(self.xList) == len(self.yList) == len(self.yaws) == len(self.currentSpeeds)
We dont use assert to validate a condition like that.

Read this https://softwareengineering.stackexchange.com/questions/225956/python-assert-vs-if-return

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +def purepursuitSteercontrol(state: State, trajectory: WayPoints, pind: int) -> Tuple[float, int]:
This function can be added to the navigation/pure_pursuit/src/pure_pursuit/pid_controller.py  file

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        self.xList: List[float] = []
instead of having two separate lists to track the x and y coordinates why cant we have a position list of type ```List[Position]``` and track the x and y together?

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        print("search Target index function is called")
Don't use print statements outside tests.

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        return ind, lookAhead  # 3ayz a2asem de le 2 functions
m3tkdsh enha m7taga tt2sm xD
lw fe dma8k 7aga go for it bs remove el comment da lol

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +    # deltaDegree = math.degrees(delta)
remove unnecessary comments

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/nodes/purepursuit_node.py
> +def plot(waypoints: WayPoints, state: State, name: str, targetInd: int) -> None:
This can be removed from the node file to a visualizer file in the src/pure_pursuit directory

2023-04-18 10:37 UTC, ahmedemad242 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +DT = rospy.get_param("/time_step")  # [s] time step
There is a better way to do that rather than having a global variable.

2023-04-19 02:38 UTC, Mohamed-alaa32 commented on .gitignore
> +navigation/pure_pursuit/tests/waypointsgen.py
Done

2023-04-19 02:40 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/launch/parameters.yaml
Done

2023-04-19 02:53 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        print("search Target index function is called")
Done

2023-04-19 02:53 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        return ind, lookAhead  # 3ayz a2asem de le 2 functions
Done

2023-04-19 02:55 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +    # deltaDegree = math.degrees(delta)
Done

2023-04-19 03:05 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +    def statesCounter(self) -> int:
Done

2023-04-19 03:06 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        assert len(self.xList) == len(self.yList) == len(self.yaws) == len(self.currentSpeeds)
Done

2023-04-19 03:06 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +class States:
Done

2023-04-19 03:07 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +def purepursuitSteercontrol(state: State, trajectory: WayPoints, pind: int) -> Tuple[float, int]:
pid controller (longitudinal controller) is different from the purepursuit controller (lateral controller), they have to be in 2 different scripts

2023-04-19 03:08 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +        self.xList: List[float] = []
Done

2023-04-19 03:09 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +    def __init__(self) -> None:
Done

2023-04-19 03:09 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pure_pursuit.py
> +class States:
Done

2023-04-19 03:09 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/src/pure_pursuit/pid_controller.py
Done

2023-04-19 03:30 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/nodes/purepursuit_node.py
> +def plot(waypoints: WayPoints, state: State, name: str, targetInd: int) -> None:
Done

2023-06-22 08:48 UTC, ahmedemad242 requested changes
These are the only changes required to accept the pull request.

2023-06-22 08:48 UTC, ahmedemad242 commented on navigation/pure_pursuit/nodes/purepursuit_node.py
> +TARGETSPEED = rospy.get_param("/targetSpeed")
These params are not published by default when running the package. Please throw an error if they are not provided or fall back to a default value
![image](https://github.com/asurt-fsai/fs-system/assets/50369848/6281d4de-381b-4250-88bd-e931fff6718f)

2023-06-22 08:48 UTC, ahmedemad242 commented on navigation/pure_pursuit/tests/pid_controller_test.py
Test cases imports doesn't conform with the new file structure. Please fix that.

2023-06-22 08:48 UTC, ahmedemad242 commented on navigation/pure_pursuit/tests/purePursuit_test.py
Test cases imports doesn't conform with the new file structure. Please fix that.

2023-06-24 14:20 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/tests/pid_controller_test.py
done

2023-06-24 14:20 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/nodes/purepursuit_node.py
> +TARGETSPEED = rospy.get_param("/targetSpeed")
done

2023-06-24 14:21 UTC, Mohamed-alaa32 commented on navigation/pure_pursuit/tests/purePursuit_test.py
done

2023-06-25 05:48 UTC, ahmedemad242 requested changes
I am getting this error after running "make clean", "make build packages="pure_pursuit""

![image](https://github.com/asurt-fsai/fs-system/assets/50369848/0c620bf4-3caf-4f8e-b023-e2ad3986cd99)

Also test cases fail on running "make test packages="pure_pursuit""

![image](https://github.com/asurt-fsai/fs-system/assets/50369848/0688c866-6fc1-4d3c-8551-7a7f805408b4)

2023-06-29 08:19 UTC, ahmedemad242 approved these changes
LGTM! Good job @Mohamed-alaa32

2023-06-29 08:19 UTC, merged