Add lqr
asurt-fsai/fs-system pull request #40
Opened 2023-04-12 22:42 UTC by aminpaw

Merge LQR to Main branch

2023-04-17 02:53 UTC, Mohamed-alaa32 requested changes

2023-04-17 02:53 UTC, Mohamed-alaa32 commented on navigation/lqr/nodes/lqr_node.py
> +    return wideTrack
suggestion:
remove any algorithm/ logic from node file
put addWidth function in lqr modules files

2023-04-17 08:21 UTC, aminpaw commented on navigation/lqr/nodes/lqr_node.py
> +    return wideTrack
done

2023-04-24 12:59 UTC, ahmedemad242 requested changes

2023-04-24 12:59 UTC, ahmedemad242 commented
We will discuss the architecture in the next f2f meeting.

2023-04-29 08:10 UTC, ahmedemad242 requested changes

2023-04-30 18:34 UTC, merged