Refactor mrpython pcl
asurt-fsai/fs-system pull request #9
Opened 2022-12-17 15:41 UTC by kareemalsawah

2022-12-25 06:26 UTC, ahmedemad242 commented
I am trying to use catkin_make but getting this error 
![image](https://user-images.githubusercontent.com/50369848/209458926-27a983f0-8cb6-43cf-9935-33d7acb7d3a3.png)

2022-12-25 06:42 UTC, ahmedemad242 commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        Transform a ros message of type LandmarkArray from a frame to anoterh
Correct spelling of the comment

2022-12-25 06:45 UTC, ahmedemad242 commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        Transform a ros message of type LandmarkArray from a frame to anoterh
in all of the following functions as well

2022-12-25 10:15 UTC, kareemalsawah commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        Transform a ros message of type LandmarkArray from a frame to anoterh
Done fixing catkin issue and spelling mistakes.

2022-12-29 13:40 UTC, ahmedemad242 requested changes

2022-12-29 13:40 UTC, ahmedemad242 commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +class TFHelper:
Do you think this is the best structure to build the TFHelper class?
I feel like with the current design, it will be connected to the whole system and this will cause problems

2022-12-29 13:42 UTC, kareemalsawah commented on perception/mrpython-pcl/testing/savingSnapshot.py
> +def main() -> None:
They are needed to run the tests. They are snapshots from a full bag. If we don't track the npy files, running the LidarPipeline_test would require the full bag.

2022-12-29 13:44 UTC, kareemalsawah commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +class TFHelper:
We are not expecting any messages to be added to the TFHelper. If in the future messages are needed, we will change the design to have a separate class for each message and the TFHelper will include objects from all these classes by composition and choose the appropriate one to use when called.

2022-12-29 13:48 UTC, ahmedemad242 commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +class TFHelper:
LGTM

2022-12-29 13:51 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/ros/Builders.py
> +        filterer = Filter(groundRemover, reconstructParam, viewBounds, carBounds)
Done

2022-12-29 13:52 UTC, kareemalsawah commented on perception/mrpython-pcl/README.md
> +sudo apt install python3-pcl
Done

2022-12-31 12:51 UTC, ahmedemad242 commented on perception/mrpython-pcl/testing/savingSnapshot.py
> +def main() -> None:
LGTM

2022-12-31 13:36 UTC, ahmedemad242 requested changes

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/LidarPipeline.py
> +        # cloud = self.filterer.subsample(cloud)
Cam you remove unwanted comments or leave a reason for it to be kept?

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +pcl.PointCloud = pcl.PointCloud
When I removed these lines as well as `# type: ignore[misc]`  
everything worked.

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +        Filters to point cloud to include include the viewable area (box around the origin)
include is repeated in comment 😅

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +        # cloud = cloud.extract(idx, False)
Remove the unneeded comment or add a reason for it

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/GroundRemoval/AdaptiveGroundRemoval.py
> +# These can be removed of course, they are just to make mypy happy
This error is not present for me? I will not comment on the other files related to this error until we resolve it here.

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/GroundRemoval/GroundRemovalMethod.py
> +        Removes points falling onto the ground plance
plance is a typo

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/GroundRemoval/GroundRemovalMethod.py
> +        Removes points falling onto the ground plance
this is repeated in the rest of the ground removal files

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifier.py
> +        # params = [coneCenter_x, coneCenter_y, coneCenter_z, linearization_term]
Please remove comment or add a reason to leave it

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +    # z = -(x**2 + y**2)*height**2/radius**2
Please remove comment or add a reason to leave it

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +        # print(res)
Please remove comment or add a reason to leave it.

For the plot part we can have an argument for display or not.

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +    # variancesToTest = np.arange(0.01, 0.5, 0.01).tolist()
Please remove comment or add a reason to leave it

2022-12-31 13:36 UTC, ahmedemad242 commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +This module can be used to run tests on the ConeClassiier hyperparameters
Assuming that these functions will not be used in the pipeline, is this the right module to put it in?

2022-12-31 13:54 UTC, ahmedemad242 requested changes
On cloning, the numpy module is not cloned. We can solve that by adding it to the ./intialize_project.sh
 `git clone git@github.com:asurt-fsai/ros_numpy.git $SCRIPT_DIR/dependencies/ros_numpy`

2023-01-01 17:06 UTC, RoniEmad commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        Transfomr a given numpy array from a given frame to another
the word 'Transform' is written 'Transfo.mr.'

2023-01-01 19:29 UTC, RoniEmad requested changes

2023-01-01 19:29 UTC, RoniEmad commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        """
If the transformation is not possible the function returns None (line 232) not the message as it is. same in transformMarkerArrayMsg() and transformLandmarkArrayMsg()

2023-01-01 19:29 UTC, RoniEmad commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        """
I think this function can be used directly without getMessageIn() function, is there a reason to use both ?

2023-01-05 09:59 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/LidarPipeline.py
> +        # cloud = self.filterer.subsample(cloud)
Done, https://github.com/asurt-fsai/fs-system/commit/4074efdbb3d7700406163206536af04b215ea279

2023-01-05 10:00 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +pcl.PointCloud = pcl.PointCloud
Done, https://github.com/asurt-fsai/fs-system/commit/93cd3b86b9429dca068858ecff7452ba7db84f4e, https://github.com/asurt-fsai/fs-system/commit/f5ea5be393f241cec2a0c0c17d9959d14025c91b, https://github.com/asurt-fsai/fs-system/commit/af26ec611e882fbd95df4b9924464757f0c15108

2023-01-05 10:00 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/GroundRemoval/AdaptiveGroundRemoval.py
> +# These can be removed of course, they are just to make mypy happy
Done, https://github.com/asurt-fsai/fs-system/commit/93cd3b86b9429dca068858ecff7452ba7db84f4e, https://github.com/asurt-fsai/fs-system/commit/f5ea5be393f241cec2a0c0c17d9959d14025c91b, https://github.com/asurt-fsai/fs-system/commit/af26ec611e882fbd95df4b9924464757f0c15108

2023-01-05 10:00 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +        Filters to point cloud to include include the viewable area (box around the origin)
Done, https://github.com/asurt-fsai/fs-system/commit/e07b82b12f9c838cb3bfd652893a7afeba5b6add

2023-01-05 10:00 UTC, kareemalsawah commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        Transfomr a given numpy array from a given frame to another
Done, https://github.com/asurt-fsai/fs-system/commit/e07b82b12f9c838cb3bfd652893a7afeba5b6add

2023-01-05 10:02 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/GroundRemoval/GroundRemovalMethod.py
> +        Removes points falling onto the ground plance
Done, https://github.com/asurt-fsai/fs-system/commit/e07b82b12f9c838cb3bfd652893a7afeba5b6add

2023-01-05 10:12 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +        # cloud = cloud.extract(idx, False)
Done, https://github.com/asurt-fsai/fs-system/commit/ccb5b102ff4822036ff07247bcfe2985c5d7df24

2023-01-05 10:12 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifier.py
> +        # params = [coneCenter_x, coneCenter_y, coneCenter_z, linearization_term]
Done, https://github.com/asurt-fsai/fs-system/commit/ccb5b102ff4822036ff07247bcfe2985c5d7df24

2023-01-05 10:12 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +        # print(res)
Done, https://github.com/asurt-fsai/fs-system/commit/ccb5b102ff4822036ff07247bcfe2985c5d7df24

2023-01-05 10:12 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +    # variancesToTest = np.arange(0.01, 0.5, 0.01).tolist()
Done, https://github.com/asurt-fsai/fs-system/commit/ccb5b102ff4822036ff07247bcfe2985c5d7df24

2023-01-05 10:13 UTC, kareemalsawah commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/ConeClassifier/ConeClassifierParamTuner.py
> +This module can be used to run tests on the ConeClassiier hyperparameters
Done, https://github.com/asurt-fsai/fs-system/commit/8b3ef75fcffcb554bf50803401231ba7e5bf1296

2023-01-05 10:22 UTC, kareemalsawah commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        """
Done, https://github.com/asurt-fsai/fs-system/commit/98681a262b65e360a8216e71d196394fa5efaba1

2023-01-05 10:22 UTC, kareemalsawah commented on dependencies/tf_helper/src/tf_helper/TFHelper.py
> +        """
Done, https://github.com/asurt-fsai/fs-system/commit/98681a262b65e360a8216e71d196394fa5efaba1

2023-01-08 07:46 UTC, ahmedemad242 approved these changes
I just wanted to take a moment to recognize the excellent work you did on this pull request. Thank you for writing high quality code which will shape the way of our repo!

For me the PR is ready and any changes can be done in a separate PR, waiting for another approval and your confirmation for the merge.

2023-01-26 12:24 UTC, RoniEmad commented on perception/mrpython-pcl/src/mrpython_pcl/LidarPipeline/Filter/Filter.py
> +        temprature: float, optional, default 500
temprature is a typo

2023-01-26 14:07 UTC, RoniEmad approved these changes
Thank you for your excellent work! :)

For me the PR is ready to be merged.

2023-02-01 12:51 UTC, merged